USE ts_analysis;

LOAD DATA LOCAL INFILE './resource_8.csv' IGNORE
INTO TABLE `iosections` FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './resource_9.csv' IGNORE
INTO TABLE `iosections` FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './resource_10.csv' IGNORE
INTO TABLE `iosections` FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './resource_11.csv' IGNORE
INTO TABLE `iosections` FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './resource_13.csv' IGNORE
INTO TABLE `iosections` FIELDS TERMINATED BY ',' IGNORE 1 LINES;
