USE ts_analysis;

LOAD DATA LOCAL INFILE './resource_8.csv' REPLACE
INTO TABLE `ts_patterns` FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './resource_9.csv' REPLACE
INTO TABLE `ts_patterns` FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './resource_10.csv' REPLACE
INTO TABLE `ts_patterns` FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './resource_11.csv' REPLACE
INTO TABLE `ts_patterns` FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './resource_13.csv' REPLACE
INTO TABLE `ts_patterns` FIELDS TERMINATED BY ',' IGNORE 1 LINES;
